### ISSUE TITLE
Unable to view PL-2

### ISSUE THREAD

**Issue by makefu** [GovReady/800-53-server#28]
http://800-53.govready.com/control?id=PL-2 seems to be broken with:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "web/800-53-server.py", line 194, in control
    sc_desc = use_org_name(sc.description.encode('utf-8'), project['organization']['name'])
  File "lib/utilities.py", line 20, in use_org_name
    text = text.replace(u'The organization', "The organization %s" % org_name)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 124: ordinal not in range(128)
```

**Comment by gregelin** [comment]
@makefu Issue appears to be a bad character in the source data. I'll look into it.
